
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package com.desenvolvimento;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SYM_ARROW_UNDIR = 10;
  public static final int KW_EDGE = 4;
  public static final int KW_UNDIRECTED = 8;
  public static final int KW_ADJACENCY = 6;
  public static final int EOF = 0;
  public static final int KW_DIRECTED = 7;
  public static final int KW_GRAPH = 2;
  public static final int ID = 11;
  public static final int KW_VERTEX = 3;
  public static final int KW_PRINT = 5;
  public static final int error = 1;
  public static final int SYM_ARROW_DIR = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "KW_GRAPH",
  "KW_VERTEX",
  "KW_EDGE",
  "KW_PRINT",
  "KW_ADJACENCY",
  "KW_DIRECTED",
  "KW_UNDIRECTED",
  "SYM_ARROW_DIR",
  "SYM_ARROW_UNDIR",
  "ID"
  };
}

